name: tutorials-env

channels:
  - pytorch
  - defaults
  
dependencies:
  - numpy=1.19.5
  - pandas=1.2.1
  - xarray=0.16.2
  - pytorch=1.7.1
  - scikit-learn=0.22
  - matplotlib=3.1.3
  - tqdm=4.42.1